### PR TITLE
TokenUsage when using streaming

### PR DESCRIPTION
**Pull request by linusbierhoff**
- added the possibility to set the option _**include_usage**_ when streaming 
- handling the usage message chunk

- currently only for OpenAI, I don't know how Claude handles usage when streaming

### CODE REVIEW

**Comment by linusbierhoff** [comment]
Does anyone know how to get the usage when using Claude and Ollama?

**Comment by prabirshrestha** [comment]
I'm ok if we do not support others yet.

**Comment by linusbierhoff** [comment]
> I'm ok if we do not support others yet.

Alright

**Comment by prabirshrestha** [comment]
@linusbierhoff can you rebase/merge with latest main branch.

**Comment by linusbierhoff** [comment]
Can someone please check if we can merge?

**Pull request merged**
