### PR TITLE
Changed Exclude String filters in favour of Callback Functions.

### PR DESCRIPTION
**Pull request by aliumujib**
Context:

Relates to https://github.com/Abraxas-365/langchain-rust/issues/203

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Can we use a callback function instead to filter? This allows it to easily be customizable to any logic.

**Comment by aliumujib** [comment]
> Can we use a callback function instead to filter? This allows it to easily be customizable to any logic.

Great idea! @prabirshrestha . I have updated the PR to use a callback function.

**Comment by prabirshrestha** [comment]
Can we combine fille filter and dir filter together and take an object instead of &str. In the future we may have other options such as symbolic link.

**Comment by aliumujib** [comment]
> Can we combine fille filter and dir filter together and take an object instead of &str. In the future we may have other options such as symbolic link.

Done! @prabirshrestha

**Comment by prabirshrestha** [comment]
Merged. Thanks!

**Pull request merged**
